"""add recommended_alternatives to dictionaries and pending_dictionary_additions

Dictionary flags are deterministic, so their rewrites are curated rather than generated by the
Recommendations Agent (ADR 0012). This adds the storage on the live lexicon and on the growth
queue (so an approved entry carries the Proposer's rewrites), and seeds the SG lexicon with
TAFEP-aligned neutral phrasings. Additive; the downgrade drops both columns.

Revision ID: 0019_dictionary_recs
Revises: 0018_add_jd_criteria_drafter
Create Date: 2026-07-05
"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019_dictionary_recs"
down_revision: str | None = "0018_add_jd_criteria_drafter"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (category, lemma_key) -> curated neutral rewrites. Keyed on the seeded lemma_key (0002).
_ALTERNATIVES: dict[tuple[str, str], list[str]] = {
    ("gender", "female working environment"): [
        "team-oriented environment",
        "collaborative workplace",
    ],
    ("gender", "masculine"): ["assertive", "results-driven"],
    ("gender", "preferably female"): ["open to applicants of any gender"],
    ("age", "digital native"): ["digitally fluent", "comfortable with current tools"],
    ("age", "mature"): ["experienced", "established professional"],
    ("age", "season"): ["experienced", "established professional"],
    ("age", "young"): ["motivated", "enthusiastic"],
    ("age", "youthful"): ["motivated", "enthusiastic"],
    ("race", "chinese only"): ["open to applicants of all backgrounds"],
    ("race", "chinese speak environment"): [
        "Mandarin-speaking role (only where the job requires it)"
    ],
    ("race", "indian only"): ["open to applicants of all backgrounds"],
    ("race", "malay only"): ["open to applicants of all backgrounds"],
    ("nationality", "foreigner"): ["applicants of any nationality with valid work authorisation"],
    ("nationality", "non singaporean"): ["applicants of any nationality"],
    ("nationality", "work pass holder"): ["applicants eligible to work in Singapore"],
    ("religion", "buddhist only"): ["open to applicants of all faiths"],
    ("religion", "christian only"): ["open to applicants of all faiths"],
    ("religion", "hindu only"): ["open to applicants of all faiths"],
    ("religion", "muslim only"): ["open to applicants of all faiths"],
    ("religion", "prayer break"): ["standard rest breaks", "flexible break arrangements"],
    ("disability", "able bodied"): ["able to perform the essential job functions"],
    ("disability", "no disability"): ["able to perform the role with reasonable accommodation"],
    ("disability", "no health issue"): [
        "able to meet the role's requirements with reasonable accommodation"
    ],
    ("disability", "physically fit and healthy"): [
        "able to perform the physical requirements of the role"
    ],
    ("family_status", "bachelor"): ["fully committed to the role's requirements"],
    ("family_status", "family commitment"): ["available for the role's stated schedule"],
    ("family_status", "maternity leave"): [
        "assess candidates on merit, regardless of anticipated leave"
    ],
    ("family_status", "newly marry"): ["assess candidates on merit, regardless of marital status"],
    ("family_status", "pregnant"): ["assess candidates on merit, regardless of pregnancy"],
}


def upgrade() -> None:
    for table in ("dictionaries", "pending_dictionary_additions"):
        op.add_column(
            table,
            sa.Column(
                "recommended_alternatives",
                postgresql.JSONB,
                nullable=False,
                server_default=sa.text("'[]'::jsonb"),
            ),
        )

    bind = op.get_bind()
    stmt = sa.text(
        "UPDATE dictionaries SET recommended_alternatives = CAST(:alts AS JSONB) "
        "WHERE region_code = 'SG' AND category::text = :cat AND lemma_key = :lk"
    )
    for (category, lemma_key), alternatives in _ALTERNATIVES.items():
        bind.execute(stmt, {"alts": json.dumps(alternatives), "cat": category, "lk": lemma_key})


def downgrade() -> None:
    op.drop_column("pending_dictionary_additions", "recommended_alternatives")
    op.drop_column("dictionaries", "recommended_alternatives")
